#ifndef SCANNER_H_INCLUDED
#define SCANNER_H_INCLUDED

#define ESTADO_SIN_DEFINIR -1
#define CANT_ESTADOS_ACEPTORES 5

#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>

typedef enum
{ 
    TOKEN_IDENTIFICADOR, 
    TOKEN_CONSTANTE_ENTERA, 
    TOKEN_NUMERAL,
    TOKEN_ERROR, 
    TOKEN_FDT 
} TOKEN;

typedef enum
{ 
    CARACTER_NUMERAL = 0,
    CARACTER_DIGITO,
    CARACTER_LETRA, 
    CARACTER_OTRO,
    CARACTER_ESPACIO,
    CARACTER_FIN_DE_ARCHIVO // EOF
} CARACTER;

typedef enum
{ 
    ESTADO_INICIAL = 0, 
    ESTADO_INTERMEDIO_IDENTIFICADOR,
    ESTADO_INTERMEDIO_CONSTANTE_ENTERA,
    ESTADO_INTERMEDIO_ERROR,
    ESTADO_ACEPTOR_IDENTIFICADOR,
    ESTADO_ACEPTOR_CONSTANTE_ENTERA,
    ESTADO_ACEPTOR_ERROR,
    ESTADO_ACEPTOR_NUMERAL,
    ESTADO_ACEPTOR_EOF
} ESTADO;

TOKEN scanner();

#endif